#!/usr/bin/env bash

set -euo pipefail

export HUGO_FLAVOUR="hugo_extended"

rm -fr *.deb
wget --no-clobber http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb
wget --no-clobber https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_FLAVOUR}_${HUGO_VERSION}_Linux-64bit.deb
find -name '*.deb' -exec dpkg -x {} $(pwd)/tmp \;
rm -fr *.deb

env LD_LIBRARY_PATH="$(pwd)/tmp/usr/lib/x86_64-linux-gnu" \
	$(pwd)/tmp/usr/local/bin/hugo
